name: Deploy Databricks Bundle

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment target'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - uat
          - psup
          - prod

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Databricks CLI
      uses: databricks/setup-cli@main
    
    - name: Validate bundle
      run: databricks bundle validate

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Databricks CLI
      uses: databricks/setup-cli@main
    
    - name: Deploy to selected target
      run: databricks bundle deploy --target ${{ github.event.inputs.target }}
